import { LegalShell, P, H2 } from '../shell'

export const metadata = { title: 'Terms of Service — Voyce' }

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" updated="2026-06-18">
      <P>
        These terms govern your use of Voyce. This is a working draft intended to be reviewed by counsel
        before commercial launch.
      </P>

      <H2>The service</H2>
      <P>
        Voyce produces draft content in your brand voice, delivers it for your review, and — where you
        connect a channel — publishes content you approve. Subscriptions are billed per the plan you
        select. The billing unit is the Content Action: one delivered content item.
      </P>

      <H2>AI-generated content &amp; your review</H2>
      <P>
        All content is generated by AI and is provided for your review. You are responsible for reviewing
        and approving content before it is published. Approval is your authorization to publish. Included
        revision rounds are defined by your plan; further changes may require a change order.
      </P>

      <H2>Autonomous publishing &amp; liability</H2>
      <P>
        Manual review is the default. Any autonomous-publishing setting (where content publishes without
        per-item approval) requires a separate, explicit opt-in and is available only after a track record
        of approvals. When autonomous publishing is enabled, published content carries an AI-assisted
        disclosure where required, and you retain a veto window to retract. To the extent permitted by law,
        you remain responsible for content you authorize Voyce to publish on your behalf, whether per-item
        or autonomously; Voyce is not liable for the consequences of publishing approved or
        autonomously-authorized content.
      </P>

      <H2>Acceptable use</H2>
      <P>
        You will not use Voyce to produce unlawful, deceptive, or infringing content, and you confirm you
        have the rights to any material (including writing samples and source content) you provide.
      </P>

      <H2>Cancellation</H2>
      <P>
        You may cancel at any time; cancellation stops future production and billing at the end of the
        current period. See the Privacy Policy for data handling and deletion.
      </P>
    </LegalShell>
  )
}
